// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tatpertvicmrravewuml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhdHBlcnR2aWNtcnJhdmV3dW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzYwNTEsImV4cCI6MjA2MTQxMjA1MX0.rng73JXGF-ra5N8Gu3S4qrnzJWd8Hqks2mKDSOavFtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);